### ISSUE TITLE
Emulate and run are not working properly.

### ISSUE THREAD

**Issue by Vincent-Alexandrine** [scopsy/ionic-webpack-es6-example#1]
Hey, 

I'm really interested into this repo with ionic with webpack, It works like a charm on browser.
My issue is that it's not running and not emulating correctly. The first html is there but not a single drop of javascript. A similar issue I had in another project was occuring when I had some es6 stuff in my code : which in this case is suppose to be transpiled with babel.

I'd like to know if you have also the same issue, and if you might have an idea of how it happens.

Thanks !

**Comment by rcenter** [comment]
Hey, Have you tried running "gulp webpack" ? This will compile the code to distribution, since when gulp work in develop it compiles in memory. In our dev environment I work from src folder(all the code is there) And when i run "gulp webpack" I compile everything to www folder. 

Let me know if you need some code examples.

**Comment by Vincent-Alexandrine** [comment]
Apparently it was exactly what was missing. I'm not used to gulp and are more interested into webpack, which makes me ignore gulp commands. 
Thanks a lot !
